// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CleanArchitecture.ApplicationCore.Entities;

public partial class Album
{
    public Guid AlbumId { get; set; }

    public string Name { get; set; }

    public DateTime ReleasedDate { get; set; }

    public Guid ArtistId { get; set; }

    public int GenreId { get; set; }

    public virtual Artist Artist { get; set; }

    public virtual Genre Genre { get; set; }
}