// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CleanArchitecture.ApplicationCore.Entities;

public partial class Artist
{
    public Guid ArtistId { get; set; }

    public string Name { get; set; }

    public DateTime? ActiveFrom { get; set; }

    public virtual ICollection<Album> Albums { get; set; } = new List<Album>();
}