// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CleanArchitecture.ApplicationCore.Entities;

public partial class Genre
{
    public int GenreId { get; set; }

    public string GenreName { get; set; }

    public virtual ICollection<Album> Albums { get; set; } = new List<Album>();
}